// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: elliptics
#ifndef GRPC_elliptics__INCLUDED
#define GRPC_elliptics__INCLUDED

#include "elliptics_generated.h"
#include "flatbuffers/grpc.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Elliptics final {
 public:
  static constexpr char const* service_full_name() {
    return "Elliptics";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Lookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, flatbuffers::grpc::Message<LookupResponse>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>> AsyncLookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>>(AsyncLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>> PrepareAsyncLookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>>(PrepareAsyncLookupRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>* AsyncLookupRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::grpc::Message<LookupResponse>>* PrepareAsyncLookupRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Lookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, flatbuffers::grpc::Message<LookupResponse>* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>> AsyncLookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>>(AsyncLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>> PrepareAsyncLookup(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>>(PrepareAsyncLookupRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>* AsyncLookupRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< flatbuffers::grpc::Message<LookupResponse>>* PrepareAsyncLookupRaw(::grpc::ClientContext* context, const flatbuffers::grpc::Message<LookupRequest>& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Lookup_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Lookup(::grpc::ServerContext* context, const flatbuffers::grpc::Message<LookupRequest>* request, flatbuffers::grpc::Message<LookupResponse>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Lookup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* context, const flatbuffers::grpc::Message<LookupRequest>* request, flatbuffers::grpc::Message<LookupResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLookup(::grpc::ServerContext* context, flatbuffers::grpc::Message<LookupRequest>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::grpc::Message<LookupResponse>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_Lookup<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Lookup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* context, const flatbuffers::grpc::Message<LookupRequest>* request, flatbuffers::grpc::Message<LookupResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Lookup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< flatbuffers::grpc::Message<LookupRequest>, flatbuffers::grpc::Message<LookupResponse>>(std::bind(&WithStreamedUnaryMethod_Lookup<BaseClass>::StreamedLookup, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* context, const flatbuffers::grpc::Message<LookupRequest>* request, flatbuffers::grpc::Message<LookupResponse>* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLookup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< flatbuffers::grpc::Message<LookupRequest>,flatbuffers::grpc::Message<LookupResponse>>* server_unary_streamer) = 0;
  };
  typedef   WithStreamedUnaryMethod_Lookup<  Service   >   StreamedUnaryService;
  typedef   Service   SplitStreamedService;
  typedef   WithStreamedUnaryMethod_Lookup<  Service   >   StreamedService;
};


#endif  // GRPC_elliptics__INCLUDED
